apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: back
  template:
    metadata:
      labels:
        component: back
    spec:
      containers:
        - name: back-container
          image: mo29172/unionista_back:latest
          ports:
            - containerPort: 3000