apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: back_db
  template:
    metadata:
      labels:
        component: back_db
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
      containers:
        - name: db-container
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
              subPath: db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: back-envs
                  key: TYPEORM_USERNAME  
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-envs
                  key: TYPEORM_PASSWORD  
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: back-envs
                  key: TYPEORM_DATABASE 
  