name: CI - PREPROD-BACK
on:
  push:
    branches: [dev]

jobs:
  deploy:
    environment: preprod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PREPROD_SSH_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
        shell: bash
        env:
          PREPROD_SSH_KEY: ${{secrets.PREPROD_PUBLIC_SSH_KEY}}

      - name: Export environment variables
        run: |
          echo PREPROD_PORT="$PREPROD_PORT" > ./.env
        env:
          PREPROD_PORT: "${{ secrets.PREPROD_PORT }}"

      - name: copy .env file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PREPROD_HOST }}
          username: ${{ secrets.PREPROD_USER }}
          key: ${{ secrets.PREPROD_SSH_KEY }}
          source: ".env"
          target: "/srv/back/source"

      - name: Install PM2
        run: npm i pm2 --force

      - name: Deploy
        run: npm run deploy-preprod
