name: CI - PREPROD-BACK
on:
  push:
    branches: [dev]

jobs:
  deploy:
    environment: preprod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PREPROD_SSH_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          PREPROD_SSH_KEY: ${{secrets.PREPROD_SSH_KEY}}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Export environment variables
        run: |
          echo PREPROD_PORT="$PREPROD_PORT" > ./.env
          echo NGINX_STATIC_LOCATION="$NGINX_STATIC_LOCATION" >> ./.env
          echo NEST_START_CMD="$NEST_START_CMD" >> ./.env
          
        env:
          PREPROD_PORT: '${{ secrets.PREPROD_PORT }}'
          NGINX_STATIC_LOCATION: '${{ secrets.NGINX_STATIC_LOCATION }}'
          NEST_START_CMD: '${{ secrets.NEST_START_CMD }}'

      - name: copy .env file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PREPROD_HOST }}
          username: ${{ secrets.PREPROD_USER }}
          key: ${{ secrets.PREPROD_SSH_KEY }}
          # password: ${{ secrets.PREPROD_PASSWORD }}
          source: '.env'
          target: '/srv/back/source'

      - name: Install PM2
        run: npm i pm2 --force

      - name: Deploy
        run: |
          npm run deploy-preprod
